### ISSUE TITLE
What is the CPU type and base frequency? Can 90% x8 cpu be used instead of 17% x 32 cpu?

### ISSUE THREAD

**Issue by web-apply** [appwrite/realtime-1-million#4]
@TorstenDittmann 
Thanks for the test. There's something I'm wondering about. According to the test results, a minimum of 16 gb ram is required. However, the 32 core usage rate is low. In theory 17% > 32cpu == 100% 5.44 cpu. So can we achieve these results on an 8-core server with a high 90%++ CPU usage rate?

In short, 8 core - 24gb ram machine can handle this load easily with 90% and below usage rate?

**Comment by TorstenDittmann** [comment]
Hey, sorry. This issue got kind of lost.

You are correct indeed, but we have to remember that predictions like this are theoretical and a lot more factors come into play.
